name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip git python3-pip build-essential
        pip install buildozer

    - name: Build APK
      run: |
        sudo apt install -y libtool libffi-dev python3-dev \
          build-essential autoconf automake cmake pkg-config zlib1g-dev \
          libncurses5 libncurses5-dev libstdc++6 libssl-dev

        pip install Cython==0.29.36
        pip install --upgrade buildozer

        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: KYC-App
        path: bin/*.apk
